[common]
from_x_high = 52
from_y_high = 75
to_x_high = 52
to_y_high = 75
from_x_low = 63
from_y_low = 82
to_x_low = 72
to_y_low = 91
map_type = "LINK_PROFILE"
overlay_contours = true
grid_width_m = 5.0
grid_font_size_m = 100.0
grid_text_margin_m = 50.0
grid_label_bg_padding_m = 10.0
display_grid = true
mask_opacity = 0.35

[helmert]
enabled = true
dx = -50.957
dy = -39.724
dz = -76.877
rx_as = 2.33295
ry_as = 2.13987
rz_as = -2.03005
ds_ppm = -1.43065

[control_point]
enabled = true
x = 5267000
y = 7587000
name = "Тополь"

[radio_horizon]
antenna_height_m = 10.0
max_flight_height_m = 500.0
uav_height_reference = "control_point"
overlay_alpha = 0.4

[radar_coverage]
azimuth_deg = 223.0
sector_width_deg = 90.0
elevation_min_deg = 1.0
elevation_max_deg = 30.0
max_range_km = 15.0
target_height_min_m = 30.0
target_height_max_m = 500.0

[link_profile]
point_a_x = 5266671
point_a_y = 7585412
point_a_name = "Лютик"
point_b_x = 5269012
point_b_y = 7588988
point_b_name = "Одуванчик"
freq_mhz = 900.0
antenna_a_m = 10.0
antenna_b_m = 10.0
