from_x_high = 53
from_y_high = 74
to_x_high = 53
to_y_high = 74
from_x_low = 52
from_y_low = 3
to_x_low = 71
to_y_low = 22
output_path = "../maps/map.jpg"
map_type = "HYBRID"
overlay_contours = true
grid_width_m = 2.0
grid_font_size_m = 100.0
grid_text_margin_m = 50.0
grid_label_bg_padding_m = 10.0
display_grid = true
mask_opacity = 0.35
jpeg_quality = 100
brightness = 1.0
contrast = 1.0
saturation = 0.69
helmert_dx = -50.957
helmert_dy = -39.724
helmert_dz = -76.877
helmert_rx_as = 2.33295
helmert_ry_as = 2.13987
helmert_rz_as = -2.03005
helmert_ds_ppm = -1.43065
control_point_enabled = false
control_point_x = 5415000
control_point_y = 7440000
