from_x_high = 54
from_y_high = 74
to_x_high = 54
to_y_high = 74
from_x_low = 14
from_y_low = 34
to_x_low = 21
to_y_low = 48
output_path = "../maps/map.jpg"
grid_width_px = 10
grid_font_size = 86
grid_text_margin = 43
grid_label_bg_padding = 6
mask_opacity = 0.24
jpeg_quality = 95
brightness = 1.0
contrast = 1.0
saturation = 1.0

map_type = "SATELLITE"