from_x_high = 53
from_y_high = 73
to_x_high = 54
to_y_high = 74
from_x_low = 95
from_y_low = 90
to_x_low = 7
to_y_low = 0
output_path = "../maps/map.jpg"
map_type = "SATELLITE"
overlay_contours = false
grid_width_px = 5
grid_font_size = 86
grid_text_margin = 43
grid_label_bg_padding = 6
mask_opacity = 0.35
jpeg_quality = 95
brightness = 1.0
contrast = 1.0
saturation = 1.0

#helmert_dx = 13.0
#helmert_dy = -122.0
#helmert_dz = -94.0
#helmert_rx_as = 0.0
#helmert_ry_as = 0.0
#helmert_rz_as = 0.0
#helmert_ds_ppm = 0.0

helmert_dx = -92.388442
helmert_dy = -101.261562
helmert_dz = 0.000000
helmert_rx_as = 0.000000
helmert_ry_as = 0.000000
helmert_rz_as = 0.799724
helmert_ds_ppm = -0.161760

control_point_enabled = true
control_point_x = 5401816
control_point_y = 7395729
