from_x_high = 61
from_y_high = 73
to_x_high = 62
to_y_high = 74
from_x_low = 56
from_y_low = 90
to_x_low = 10
to_y_low = 37
output_path = "../maps/moscow.jpg"
grid_width_px = 5
grid_font_size = 86
grid_text_margin = 43
grid_label_bg_padding = 6
mask_opacity = 0.35
jpeg_quality = 95
brightness = 1.0
contrast = 1.0
saturation = 1.0

map_type = "SATELLITE"