from_x_high = 52
from_y_high = 75
to_x_high = 52
to_y_high = 75
from_x_low = 26
from_y_low = 40
to_x_low = 43
to_y_low = 64
output_path = "../maps/map.png"
grid_width_px = 4
grid_font_size = 86
grid_text_margin = 43
grid_label_bg_padding = 6
mask_opacity = 0.35
