from_x_high = 54
from_y_high = 74
to_x_high = 54
to_y_high = 74
from_x_low = 21
from_y_low = 48
to_x_low = 22
to_y_low = 49
output_path = "../maps/map.jpg"
map_type = "SATELLITE"
overlay_contours = false
grid_width_px = 5
grid_font_size = 120
grid_text_margin = 43
grid_label_bg_padding = 6
mask_opacity = 0.35
jpeg_quality = 95
brightness = 1.0
contrast = 1.0
saturation = 1.0

helmert_dx = 10.0
helmert_dy = -185.0
helmert_dz = -94.0
helmert_rx_as = 0.0
helmert_ry_as = 0.0
helmert_rz_as = 0.0
helmert_ds_ppm = 0.0


control_point_enabled = true
control_point_x = 5421208
control_point_y = 7448190
